### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by Kadantte** [SingularityF/PixivWallpaper#22]
Can you make the GUI with Dark Theme / Mode?

**Comment by SingularityF** [comment]
> 
> 
> Can you make the GUI with Dark Theme / Mode?

Added to backlog. Though the feature won't come any time soon.
If you don't want to wait, you can always change the html/css code in 
`PixivWallpaper/Client/ElectronClient/mainWindow.html`
Building the Electron app is very straightforward.

**Comment by Kadantte** [comment]
#26 Here we Go!
